branch-defaults:
  master:
    environment: you2-web2
    group_suffix: null
global:
  application_name: youtube-down
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2018.03 v4.14.4 running Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
